-- CreateTable
CREATE TABLE "KajianRiwayatMenyusui" (
    "id" TEXT NOT NULL,
    "no_registrasi" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "pemberianMakanASI" BOOLEAN NOT NULL DEFAULT false,
    "pemberianMakanSusuLain" BOOLEAN NOT NULL DEFAULT false,
    "keteranganSusuLain" TEXT,
    "frekuensiMenyusui" TEXT,
    "keteranganFrekuensiMenyusui" TEXT,
    "lamaMenyusui" TEXT,
    "menyusui" TEXT,
    "menyusuiMalamHari" TEXT,
    "jumlahFrekuensiSusuLain" TEXT,
    "cairanTambahanKapanDimulai" TEXT,
    "cairanTambahanApaYangDiberikan" TEXT,
    "cairanTambahanFrekuensiPemberian" TEXT,
    "cairanTambahanBerapaBanyak" TEXT,
    "makananTambahanKapanDimulai" TEXT,
    "makananTambahanApaYangDiberikan" TEXT,
    "makananTambahanFrekuensiPemberian" TEXT,
    "makananTambahanBerapaBanyak" TEXT,
    "menggunakanBotol" TEXT,
    "keteranganBotol" TEXT,
    "bbSaatLahir" INTEGER,
    "bbSaatIni" INTEGER,
    "perubahanBB" TEXT,
    "jenisKelahiranPrematur" BOOLEAN NOT NULL DEFAULT false,
    "jenisKelahiranKembar" BOOLEAN NOT NULL DEFAULT false,
    "frekuensiBAK" TEXT,
    "warnaBAK" TEXT,
    "frekuensiBAB" TEXT,
    "kosistensiBAB" TEXT,
    "perilakuMakan" TEXT,
    "perilakuTidur" TEXT,
    "perilakuMenangis" TEXT,
    "riwayatSakit" TEXT,
    "kelainanBawaan" TEXT,
    "tempatANCRS" BOOLEAN NOT NULL DEFAULT false,
    "tempatANCTPMB" BOOLEAN NOT NULL DEFAULT false,
    "tempatANCPuskesmas" BOOLEAN NOT NULL DEFAULT false,
    "tempatANCPolindes" BOOLEAN NOT NULL DEFAULT false,
    "tempatANCLainnya" BOOLEAN NOT NULL DEFAULT false,
    "tempatANCKeteranganLainnya" TEXT,
    "yangMelakukanANCDokterKandungan" BOOLEAN NOT NULL DEFAULT false,
    "yangMelakukanANCBidan" BOOLEAN NOT NULL DEFAULT false,
    "yangMelakukanANCDokterUmum" BOOLEAN NOT NULL DEFAULT false,
    "yangMelakukanANCLainnya" BOOLEAN NOT NULL DEFAULT false,
    "yangMelakukanANCKeteranganLainnya" TEXT,
    "diskusiPemberianMakan" TEXT,
    "jenisPersalinan" TEXT,
    "riwayatIMD" TEXT,
    "menyusui1Jam" TEXT,
    "rawatGabung" TEXT,
    "pemberianPrelaktal" TEXT,
    "bantuanMenyusui" TEXT,
    "menerimaSampleFormula" TEXT,
    "riwayatKesehatanIbu" TEXT,
    "obatDikonsumsi" TEXT,
    "giziIbu" TEXT,
    "kebiasaanKopi" TEXT,
    "minumanAlkohol" TEXT,
    "kebiasaanMerokok" TEXT,
    "narkoba" TEXT,
    "kondisiPayudara" TEXT,
    "penggunaanKB" TEXT,
    "keteranganKB" TEXT,
    "motivasiMenyusui" TEXT,
    "jumlahAnakSebelumnya" TEXT,
    "jumlahAnakDisusui" TEXT,
    "riwayatASIEksklusif" TEXT,
    "cairanTambahanSebelumnyaKapanDimulai" TEXT,
    "cairanTambahanSebelumnyaApaYangDiberikan" TEXT,
    "cairanTambahanSebelumnyaFrekuensiPemberian" TEXT,
    "cairanTambahanSebelumnyaBerapaBanyak" TEXT,
    "makananTambahanSebelumnyaKapanDimulai" TEXT,
    "makananTambahanSebelumnyaApaYangDiberikan" TEXT,
    "makananTambahanSebelumnyaFrekuensiPemberian" TEXT,
    "makananTambahanSebelumnyaBerapaBanyak" TEXT,
    "menggunakanBotolSebelumnya" TEXT,
    "alasanBotol" TEXT,
    "pekerjaanOrangTua" TEXT,
    "keadaanEkonomi" TEXT,
    "pendidikanOrangTua" TEXT,
    "sikapKeluarga" TEXT,
    "bantuanPerawatanAnak" TEXT,
    "pertumbuhanSesuaiKurva" TEXT,

    CONSTRAINT "KajianRiwayatMenyusui_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "KajianRiwayatMenyusui_no_registrasi_key" ON "KajianRiwayatMenyusui"("no_registrasi");

-- CreateIndex
CREATE INDEX "KajianRiwayatMenyusui_no_registrasi_idx" ON "KajianRiwayatMenyusui"("no_registrasi");

-- AddForeignKey
ALTER TABLE "KajianRiwayatMenyusui" ADD CONSTRAINT "KajianRiwayatMenyusui_no_registrasi_fkey" FOREIGN KEY ("no_registrasi") REFERENCES "Registrasi"("no_registrasi") ON DELETE RESTRICT ON UPDATE CASCADE;
